0410



예외처리 

finally는 중간에 try나 catch 구문 안에 return이 있을 경우에도 실행된다.
try-catch 구분 밖의 다른 문장은 실행되지 않는다는 차이점이 있다.


class MyError(Exception):		----예외 만들기
    def __str__(self):
        return '음수 ㄴㄴ'

try:
    num = int( input('숫자입력해봐 : '))
    print('두배다 두배 : ', num*2)
    if num < 0:
        raise MyError()			----강제로 throw 날리는 것
except ValueError as e:			----특정 Exception을 잡는 것
    print(e)				----에러내용 객체화해서 찍기
    print('숫자가 아닙니다.')
except:
    print('예외가 잡혔습니다.')
else:
    print('예외가 안나야 실행')
finally:
    print('무조건 실행. 위에서 return이 있어도')



파일 IO

f = open('py06.py','r',encoding='utf-8')----파일 읽어오기
lines = f.readlines()			----readline()은 딱 한 줄만 읽어오고 readlines()는 전부 읽어와서 각 줄별로 List에 담음
for line in lines:			----for를 줄줄 돌면서 실행
    print(line)

f.close()

팁---파이썬에서는 문장이 나와야하는데 비어있어도 에러가 난다 그래서 pass가 있음


beautifulsoup4를 설치

크론탭 crontab
